# Generated by Django 4.0.4 on 2022-05-03 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(null=True, upload_to='')),
                ('foreignKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
