# Generated by Django 4.0.4 on 2022-05-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='File',
            new_name='file',
        ),
    ]
