# Generated by Django 4.0.4 on 2022-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloud', '0002_rename_file_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to='UserFiles'),
        ),
    ]
